apiVersion: v1
kind: Secret
metadata:
  name: backend
  namespace: logistics
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: WXpyQTM8KDY/TGhnXS5Vb0hBMWFvRFNYOTRPKQ==  # Base64 for password
  SPRING_DATASOURCE_USERNAME: YWRtaW4=  
