apiVersion: v1
kind: Secret
metadata:
  name: backend
  namespace: fusioniq
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: QWRtaW5AMTIz  # Base64 for "Admin@123"
  SPRING_DATASOURCE_USERNAME: YWRtaW4=  