apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: logistics
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://logistics-postgres.c52g0ciigsal.us-east-2.rds.amazonaws.com:5432/mydb"

---
apiVersion: v1
kind: Secret
metadata:
  name: backend
  namespace: logistics
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: ZGJhZG1pbg==     # base64 of 'logistics_admin'
  SPRING_DATASOURCE_PASSWORD: U2VjdXJlUGFzczEyMyE=   # base64 of 'MySecurePass123'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: logistics
  labels:
    name: backend
    project: logistics
    tier: app 
spec:
  replicas: 2
  selector:
    matchLabels: 
      name: backend
      project: logistics
      tier: app
  template: 
    metadata:
      labels: 
        name: backend
        project: logistics
        tier: app
    spec:
      containers:
      - name: backend
        image: yourdockerhub/logistics-backend:v1
        imagePullPolicy: Always
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: backend
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend
              key: SPRING_DATASOURCE_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: logistics
spec:
  selector:
    name: backend
    project: logistics
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
