apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: fusioniq
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: QWRtaW5AMTIz
  MYSQL_USER: YWRtaW4=
  MYSQL_PASSWORD: QWRtaW5AMTIz
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: fusioniq
  labels:
    app: mysql
    project: fusioniq
    tier: db
spec:
  selector:
    matchLabels:
      app: mysql
      project: fusioniq
      tier: db
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        project: fusioniq
        tier: db
    spec:
      securityContext:
        fsGroup: 999
      containers:
      - name: mysql
        image: iamroyalreddy/mysql:8.0.41
        securityContext:
          runAsUser: 999
        args: []
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: MYSQL_PASSWORD  
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql
              key: MYSQL_USER  
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 10Gi
--- 
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: fusioniq
  labels:
    app: mysql
    project: fusioniq
    tier: db
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    port: 3306 #service-port
    targetPort: 3306
  selector:
    app: mysql
    project: fusioniq
    tier: db
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  namespace: fusioniq
  labels:
    app: mysql
    project: fusioniq
    tier: db
spec:
  selector:
    app: mysql
    project: fusioniq
    tier: db
    # statefulset.kubernetes.io/pod-name: mysql-0
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-read
  namespace: fusioniq
  labels:
    app: mysql
    project: fusioniq
    tier: db
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306