apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: fusioniq
  labels:
    app: mysql
    project: fusioniq
    tier: db
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    port: 3306 #service-port
    targetPort: 3306
  selector:
    app: mysql
    project: fusioniq
    tier: db
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  namespace: fusioniq
  labels:
    app: mysql
    project: fusioniq
    tier: db
spec:
  selector:
    app: mysql
    project: fusioniq
    tier: db
    # statefulset.kubernetes.io/pod-name: mysql-0
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-read
  namespace: fusioniq
  labels:
    app: mysql
    project: fusioniq
    tier: db
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306