apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: fusioniq
  labels:
    app: mysql
    project: fusioniq
    tier: db
spec:
  selector:
    matchLabels:
      app: mysql
      project: fusioniq
      tier: db
  serviceName: "mysql"
  replicas: {{ .Values.statefulset.replicas }}
  template:
    metadata:
      labels:
        app: mysql
        project: fusioniq
        tier: db
    spec:
      securityContext:
        fsGroup: 999
      containers:
      - name: mysql
        image: "iamroyalreddy/mysql:{{ .Values.statefulset.imageVersion }}"
        securityContext:
          runAsUser: 999
        args: []
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: MYSQL_PASSWORD  
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql
              key: MYSQL_USER  
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 10Gi